// <auto-generated />
using System;
using AkataAcademy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AkataAcademy.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260224031032_EnrollmentMigration")]
    partial class EnrollmentMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AkataAcademy.Domain.BoundedContexts.Catalog.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("AkataAcademy.Domain.BoundedContexts.Catalog.Entities.CourseModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseModules");
                });

            modelBuilder.Entity("AkataAcademy.Domain.BoundedContexts.Certification.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("AkataAcademy.Domain.BoundedContexts.Enrollment.Entities.CourseEnrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("CompletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DroppedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EnrolledOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SuspendedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique();

                    b.ToTable("CourseEnrollments", (string)null);
                });

            modelBuilder.Entity("AkataAcademy.Domain.BoundedContexts.StudentManagement.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateOfBirth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("Email");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Students");
                });

            modelBuilder.Entity("AkataAcademy.Domain.BoundedContexts.Catalog.Entities.Course", b =>
                {
                    b.OwnsOne("AkataAcademy.Domain.BoundedContexts.Catalog.ValueObjects.CourseDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.OwnsOne("AkataAcademy.Domain.BoundedContexts.Catalog.ValueObjects.CourseTitle", "Title", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("AkataAcademy.Domain.BoundedContexts.Catalog.Entities.CourseModule", b =>
                {
                    b.HasOne("AkataAcademy.Domain.BoundedContexts.Catalog.Entities.Course", null)
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AkataAcademy.Domain.BoundedContexts.Catalog.ValueObjects.ModuleDuration", "Duration", b1 =>
                        {
                            b1.Property<Guid>("CourseModuleId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Minutes")
                                .HasColumnType("integer");

                            b1.HasKey("CourseModuleId");

                            b1.ToTable("CourseModules");

                            b1.WithOwner()
                                .HasForeignKey("CourseModuleId");
                        });

                    b.OwnsOne("AkataAcademy.Domain.BoundedContexts.Catalog.ValueObjects.ModuleTitle", "Title", b1 =>
                        {
                            b1.Property<Guid>("CourseModuleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CourseModuleId");

                            b1.ToTable("CourseModules");

                            b1.WithOwner()
                                .HasForeignKey("CourseModuleId");
                        });

                    b.Navigation("Duration")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("AkataAcademy.Domain.BoundedContexts.Certification.Entities.Certificate", b =>
                {
                    b.OwnsOne("AkataAcademy.Domain.BoundedContexts.Certification.ValueObjects.CourseId", "CourseId", b1 =>
                        {
                            b1.Property<Guid>("CertificateId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid");

                            b1.HasKey("CertificateId");

                            b1.ToTable("Certificates");

                            b1.WithOwner()
                                .HasForeignKey("CertificateId");
                        });

                    b.OwnsOne("AkataAcademy.Domain.BoundedContexts.Certification.ValueObjects.ExpirationDate", "ExpiresOn", b1 =>
                        {
                            b1.Property<Guid>("CertificateId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("CertificateId");

                            b1.ToTable("Certificates");

                            b1.WithOwner()
                                .HasForeignKey("CertificateId");
                        });

                    b.OwnsOne("AkataAcademy.Domain.BoundedContexts.Certification.ValueObjects.IssueDate", "IssuedOn", b1 =>
                        {
                            b1.Property<Guid>("CertificateId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("CertificateId");

                            b1.ToTable("Certificates");

                            b1.WithOwner()
                                .HasForeignKey("CertificateId");
                        });

                    b.OwnsOne("AkataAcademy.Domain.BoundedContexts.Certification.ValueObjects.StudentId", "StudentId", b1 =>
                        {
                            b1.Property<Guid>("CertificateId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid");

                            b1.HasKey("CertificateId");

                            b1.ToTable("Certificates");

                            b1.WithOwner()
                                .HasForeignKey("CertificateId");
                        });

                    b.Navigation("CourseId")
                        .IsRequired();

                    b.Navigation("ExpiresOn")
                        .IsRequired();

                    b.Navigation("IssuedOn")
                        .IsRequired();

                    b.Navigation("StudentId")
                        .IsRequired();
                });

            modelBuilder.Entity("AkataAcademy.Domain.BoundedContexts.Enrollment.Entities.CourseEnrollment", b =>
                {
                    b.OwnsOne("AkataAcademy.Domain.BoundedContexts.Enrollment.ValueObjects.ProgressIncrement", "ProgressIncrement", b1 =>
                        {
                            b1.Property<Guid>("CourseEnrollmentId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Value")
                                .HasColumnType("integer")
                                .HasColumnName("ProgressIncrement");

                            b1.HasKey("CourseEnrollmentId");

                            b1.ToTable("CourseEnrollments");

                            b1.WithOwner()
                                .HasForeignKey("CourseEnrollmentId");
                        });

                    b.OwnsOne("AkataAcademy.Domain.BoundedContexts.Enrollment.Entities.Progress", "Progress", b1 =>
                        {
                            b1.Property<Guid>("CourseEnrollmentId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid")
                                .HasColumnName("ProgressId");

                            b1.Property<int>("LessonsCompleted")
                                .HasColumnType("integer")
                                .HasColumnName("LessonsCompleted");

                            b1.HasKey("CourseEnrollmentId");

                            b1.ToTable("CourseEnrollments");

                            b1.WithOwner()
                                .HasForeignKey("CourseEnrollmentId");

                            b1.OwnsOne("AkataAcademy.Domain.BoundedContexts.Enrollment.ValueObjects.ProgressIncrement", "Increment", b2 =>
                                {
                                    b2.Property<Guid>("ProgressCourseEnrollmentId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer")
                                        .HasColumnName("ProgressIncrementValue");

                                    b2.HasKey("ProgressCourseEnrollmentId");

                                    b2.ToTable("CourseEnrollments");

                                    b2.WithOwner()
                                        .HasForeignKey("ProgressCourseEnrollmentId");
                                });

                            b1.OwnsOne("AkataAcademy.Domain.BoundedContexts.Enrollment.ValueObjects.CompletionPercentage", "Percentage", b2 =>
                                {
                                    b2.Property<Guid>("ProgressCourseEnrollmentId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Value")
                                        .HasColumnType("integer")
                                        .HasColumnName("ProgressPercentage");

                                    b2.HasKey("ProgressCourseEnrollmentId");

                                    b2.ToTable("CourseEnrollments");

                                    b2.WithOwner()
                                        .HasForeignKey("ProgressCourseEnrollmentId");
                                });

                            b1.Navigation("Increment")
                                .IsRequired();

                            b1.Navigation("Percentage")
                                .IsRequired();
                        });

                    b.OwnsOne("AkataAcademy.Domain.BoundedContexts.Enrollment.ValueObjects.EnrollmentStatus", "Status", b1 =>
                        {
                            b1.Property<Guid>("CourseEnrollmentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Status");

                            b1.HasKey("CourseEnrollmentId");

                            b1.ToTable("CourseEnrollments");

                            b1.WithOwner()
                                .HasForeignKey("CourseEnrollmentId");
                        });

                    b.Navigation("Progress")
                        .IsRequired();

                    b.Navigation("ProgressIncrement")
                        .IsRequired();

                    b.Navigation("Status")
                        .IsRequired();
                });

            modelBuilder.Entity("AkataAcademy.Domain.BoundedContexts.StudentManagement.Entities.Student", b =>
                {
                    b.OwnsOne("AkataAcademy.Domain.BoundedContexts.StudentManagement.ValueObjects.FullName", "Name", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("FirstName");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("LastName");

                            b1.HasKey("StudentId");

                            b1.ToTable("Students");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("AkataAcademy.Domain.BoundedContexts.Catalog.Entities.Course", b =>
                {
                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
