// <auto-generated />
using System;
using AkataAcademy.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AkataAcademy.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AkataAcademy.Domain.BoundedContexts.Catalog.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("AkataAcademy.Domain.BoundedContexts.Catalog.Entities.CourseModule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseModules");
                });

            modelBuilder.Entity("AkataAcademy.Domain.BoundedContexts.Certification.Entities.Certificate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("AkataAcademy.Domain.BoundedContexts.Catalog.Entities.Course", b =>
                {
                    b.OwnsOne("AkataAcademy.Domain.BoundedContexts.Catalog.ValueObjects.CourseDescription", "Description", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.OwnsOne("AkataAcademy.Domain.BoundedContexts.Catalog.ValueObjects.CourseTitle", "Title", b1 =>
                        {
                            b1.Property<Guid>("CourseId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)");

                            b1.HasKey("CourseId");

                            b1.ToTable("Courses");

                            b1.WithOwner()
                                .HasForeignKey("CourseId");
                        });

                    b.Navigation("Description")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("AkataAcademy.Domain.BoundedContexts.Catalog.Entities.CourseModule", b =>
                {
                    b.HasOne("AkataAcademy.Domain.BoundedContexts.Catalog.Entities.Course", null)
                        .WithMany("Modules")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AkataAcademy.Domain.BoundedContexts.Catalog.ValueObjects.ModuleDuration", "Duration", b1 =>
                        {
                            b1.Property<Guid>("CourseModuleId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Minutes")
                                .HasColumnType("integer");

                            b1.HasKey("CourseModuleId");

                            b1.ToTable("CourseModules");

                            b1.WithOwner()
                                .HasForeignKey("CourseModuleId");
                        });

                    b.OwnsOne("AkataAcademy.Domain.BoundedContexts.Catalog.ValueObjects.ModuleTitle", "Title", b1 =>
                        {
                            b1.Property<Guid>("CourseModuleId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CourseModuleId");

                            b1.ToTable("CourseModules");

                            b1.WithOwner()
                                .HasForeignKey("CourseModuleId");
                        });

                    b.Navigation("Duration")
                        .IsRequired();

                    b.Navigation("Title")
                        .IsRequired();
                });

            modelBuilder.Entity("AkataAcademy.Domain.BoundedContexts.Certification.Entities.Certificate", b =>
                {
                    b.OwnsOne("AkataAcademy.Domain.BoundedContexts.Certification.ValueObjects.CourseId", "CourseId", b1 =>
                        {
                            b1.Property<Guid>("CertificateId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid");

                            b1.HasKey("CertificateId");

                            b1.ToTable("Certificates");

                            b1.WithOwner()
                                .HasForeignKey("CertificateId");
                        });

                    b.OwnsOne("AkataAcademy.Domain.BoundedContexts.Certification.ValueObjects.ExpirationDate", "ExpiresOn", b1 =>
                        {
                            b1.Property<Guid>("CertificateId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("CertificateId");

                            b1.ToTable("Certificates");

                            b1.WithOwner()
                                .HasForeignKey("CertificateId");
                        });

                    b.OwnsOne("AkataAcademy.Domain.BoundedContexts.Certification.ValueObjects.IssueDate", "IssuedOn", b1 =>
                        {
                            b1.Property<Guid>("CertificateId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Value")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("CertificateId");

                            b1.ToTable("Certificates");

                            b1.WithOwner()
                                .HasForeignKey("CertificateId");
                        });

                    b.OwnsOne("AkataAcademy.Domain.BoundedContexts.Certification.ValueObjects.StudentId", "StudentId", b1 =>
                        {
                            b1.Property<Guid>("CertificateId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("Value")
                                .HasColumnType("uuid");

                            b1.HasKey("CertificateId");

                            b1.ToTable("Certificates");

                            b1.WithOwner()
                                .HasForeignKey("CertificateId");
                        });

                    b.Navigation("CourseId")
                        .IsRequired();

                    b.Navigation("ExpiresOn")
                        .IsRequired();

                    b.Navigation("IssuedOn")
                        .IsRequired();

                    b.Navigation("StudentId")
                        .IsRequired();
                });

            modelBuilder.Entity("AkataAcademy.Domain.BoundedContexts.Catalog.Entities.Course", b =>
                {
                    b.Navigation("Modules");
                });
#pragma warning restore 612, 618
        }
    }
}
